"""
Eye Gaze Tracking Constants – TrueView AI

Defines landmark indices, gaze direction enums, iris position thresholds,
attention classification boundaries, and visualization color palettes.

Architecture Note:
    These constants are calibrated for the 68-point iBUG landmark scheme
    generated by Phase 7's LandmarkExtractor. When upgrading to MediaPipe
    468-point mesh, update the eye/iris landmark indices accordingly
    (MediaPipe iris: 468-472 left, 473-477 right).
"""

# ──────────────────────────────────────────────
# Eye Landmark Indices (iBUG 68-point convention)
# ──────────────────────────────────────────────
RIGHT_EYE_INDICES = list(range(36, 42))   # Points 36-41
LEFT_EYE_INDICES  = list(range(42, 48))   # Points 42-47

# Anchor landmark indices for quick reference
RIGHT_EYE_OUTER = 36
RIGHT_EYE_INNER = 39
LEFT_EYE_INNER  = 42
LEFT_EYE_OUTER  = 45

# ──────────────────────────────────────────────
# MediaPipe 468/478 Eye Landmark Indices (6 points for EAR)
# ──────────────────────────────────────────────
# Right eye (subject's right eye, viewer's left):
# outer corner: 33, top pair: 160, 158, inner corner: 133, bottom pair: 153, 144
MEDIAPIPE_RIGHT_EYE_INDICES = [33, 160, 158, 133, 153, 144]
# Left eye (subject's left eye, viewer's right):
# inner corner: 362, top pair: 385, 387, outer corner: 263, bottom pair: 373, 380
MEDIAPIPE_LEFT_EYE_INDICES  = [362, 385, 387, 263, 373, 380]

# ──────────────────────────────────────────────
# Gaze Direction Enums
# ──────────────────────────────────────────────
class GazeDirection:
    """Enumeration of gaze direction labels."""
    CENTER  = "center"
    LEFT    = "left"
    RIGHT   = "right"
    UP      = "up"
    DOWN    = "down"
    UNKNOWN = "unknown"

# ──────────────────────────────────────────────
# Eye Status & Attention Enums
# ──────────────────────────────────────────────
class EyeStatus:
    """Enumeration of physical eye openness states."""
    OPEN             = "OPEN"
    PARTIALLY_CLOSED = "PARTIALLY_CLOSED"
    BLINKING         = "BLINKING"
    CLOSED           = "CLOSED"
    UNKNOWN          = "UNKNOWN"

class AttentionStatus:
    """Enumeration of attention classification states."""
    FOCUSED            = "focused"
    BLINKING           = "blinking"
    EYES_CLOSED        = "eyes_closed"
    DISTRACTED         = "distracted"
    LOOKING_AWAY       = "looking_away"
    FACE_NOT_DETECTED  = "face_not_detected"

class FocusState:
    """High-level focus states corresponding to proctoring policies."""
    FOCUSED           = "FOCUSED"
    BLINKING          = "BLINKING"
    EYES_CLOSED       = "EYES_CLOSED"
    OFFSCREEN         = "OFFSCREEN"
    DISTRACTED        = "DISTRACTED"
    FACE_NOT_DETECTED = "FACE_NOT_DETECTED"

# ──────────────────────────────────────────────
# Eye Openness / Aspect Ratio (EAR) Thresholds
# Calibrated for MediaPipe & geometric EAR
# ──────────────────────────────────────────────
EYE_CLOSED_THRESHOLD               = 0.21   # averageEAR <= 0.21 indicates eye closure
EYE_OPEN_THRESHOLD                 = 0.25   # averageEAR >= 0.25 indicates fully open
BLINK_MAX_DURATION_SECONDS         = 0.40   # Closures <= 0.40s (400ms) treated as natural blink
PROLONGED_CLOSURE_SECONDS          = 1.50   # Closures > 1.5s monitored internally
EYES_CLOSED_ALERT_DURATION_SECONDS = 2.50   # Sustained closures >= 2.5s trigger moderate inattention alert
EYES_CLOSED_ALERT_DURATION_MS      = 2500
MIN_FACE_CONFIDENCE                = 0.50   # Below this, face is considered UNKNOWN

# ──────────────────────────────────────────────
# Iris Position Thresholds (normalized 0.0 – 1.0)
#
# The eye bounding box is [0.0, 1.0] on both axes.
# Iris center position within this box determines
# gaze direction.
#
#  0.0 ───────── 0.35 ──── 0.65 ───────── 1.0
#  ◄── LEFT ──── │ CENTER │ ──── RIGHT ──►
#
# ──────────────────────────────────────────────
GAZE_HORIZONTAL_LEFT_THRESHOLD  = 0.38   # iris_x < 0.38 → looking off-screen LEFT
GAZE_HORIZONTAL_RIGHT_THRESHOLD = 0.62   # iris_x > 0.62 → looking off-screen RIGHT
GAZE_VERTICAL_UP_THRESHOLD      = 0.32   # iris_y < 0.32 → looking off-screen UP
GAZE_VERTICAL_DOWN_THRESHOLD    = 0.68   # iris_y > 0.68 → looking off-screen DOWN

# Confidence scaling factors
GAZE_CENTER_CONFIDENCE    = 0.95   # High confidence when centered
GAZE_DIRECTION_CONFIDENCE = 0.85   # Slightly lower for directional gazes
GAZE_EXTREME_CONFIDENCE   = 0.70   # Lower for extreme positions

# ──────────────────────────────────────────────
# Attention Analysis Parameters
# ──────────────────────────────────────────────
ATTENTION_WINDOW_SIZE     = 90     # Rolling window (frames) ≈ 3 sec @ 30 FPS
ATTENTION_FOCUSED_THRESHOLD   = 70.0   # Score ≥ 70% → FOCUSED
ATTENTION_DISTRACTED_THRESHOLD = 40.0  # Score 40-69% → DISTRACTED
                                        # Score < 40%  → LOOKING_AWAY

# Focus duration tracking
FOCUS_STREAK_RESET_FRAMES = 10    # Consecutive non-center frames to reset streak

# ──────────────────────────────────────────────
# Visualization Colors (BGR for OpenCV)
# ──────────────────────────────────────────────
VIS_COLORS = {
    "eye_contour":      (255, 200, 50),    # Cyan-ish blue
    "iris_center":      (0, 255, 200),     # Bright green-yellow
    "iris_ring":        (0, 255, 255),     # Yellow
    "gaze_arrow":       (100, 255, 100),   # Green
    "focus_indicator":  (0, 255, 0),       # Pure green (focused)
    "distracted_indicator": (0, 200, 255), # Orange
    "away_indicator":   (0, 0, 255),       # Red
    "text_bg":          (30, 30, 30),      # Dark background for text
    "text_fg":          (255, 255, 255),   # White text
}

# Arrow / indicator sizing
GAZE_ARROW_LENGTH    = 40     # pixels
GAZE_ARROW_THICKNESS = 2
IRIS_DOT_RADIUS      = 3
EYE_CONTOUR_THICKNESS = 1

# Focus indicator position (top-right corner offset)
FOCUS_INDICATOR_X_OFFSET = 20
FOCUS_INDICATOR_Y_OFFSET = 30
FOCUS_INDICATOR_RADIUS   = 8
