"""
Eye Gaze Tracking Constants – TrueView AI

Defines landmark indices, gaze direction enums, iris position thresholds,
attention classification boundaries, and visualization color palettes.

Architecture Note:
    These constants are calibrated for the 68-point iBUG landmark scheme
    generated by Phase 7's LandmarkExtractor. When upgrading to MediaPipe
    468-point mesh, update the eye/iris landmark indices accordingly
    (MediaPipe iris: 468-472 left, 473-477 right).
"""

# ──────────────────────────────────────────────
# Eye Landmark Indices (iBUG 68-point convention)
# ──────────────────────────────────────────────
RIGHT_EYE_INDICES = list(range(36, 42))   # Points 36-41
LEFT_EYE_INDICES  = list(range(42, 48))   # Points 42-47

# Anchor landmark indices for quick reference
RIGHT_EYE_OUTER = 36
RIGHT_EYE_INNER = 39
LEFT_EYE_INNER  = 42
LEFT_EYE_OUTER  = 45

# ──────────────────────────────────────────────
# Gaze Direction Enums
# ──────────────────────────────────────────────
class GazeDirection:
    """Enumeration of gaze direction labels."""
    CENTER = "center"
    LEFT   = "left"
    RIGHT  = "right"
    UP     = "up"
    DOWN   = "down"

# ──────────────────────────────────────────────
# Attention Status Enums
# ──────────────────────────────────────────────
class AttentionStatus:
    """Enumeration of attention classification states."""
    FOCUSED      = "focused"
    DISTRACTED   = "distracted"
    LOOKING_AWAY = "looking_away"

# ──────────────────────────────────────────────
# Iris Position Thresholds (normalized 0.0 – 1.0)
#
# The eye bounding box is [0.0, 1.0] on both axes.
# Iris center position within this box determines
# gaze direction.
#
#  0.0 ───────── 0.35 ──── 0.65 ───────── 1.0
#  ◄── LEFT ──── │ CENTER │ ──── RIGHT ──►
#
# ──────────────────────────────────────────────
GAZE_HORIZONTAL_LEFT_THRESHOLD  = 0.35   # iris_x < this → looking LEFT
GAZE_HORIZONTAL_RIGHT_THRESHOLD = 0.65   # iris_x > this → looking RIGHT
GAZE_VERTICAL_UP_THRESHOLD      = 0.30   # iris_y < this → looking UP
GAZE_VERTICAL_DOWN_THRESHOLD    = 0.70   # iris_y > this → looking DOWN

# Confidence scaling factors
GAZE_CENTER_CONFIDENCE    = 0.95   # High confidence when centered
GAZE_DIRECTION_CONFIDENCE = 0.85   # Slightly lower for directional gazes
GAZE_EXTREME_CONFIDENCE   = 0.70   # Lower for extreme positions

# ──────────────────────────────────────────────
# Attention Analysis Parameters
# ──────────────────────────────────────────────
ATTENTION_WINDOW_SIZE     = 90     # Rolling window (frames) ≈ 3 sec @ 30 FPS
ATTENTION_FOCUSED_THRESHOLD   = 70.0   # Score ≥ 70% → FOCUSED
ATTENTION_DISTRACTED_THRESHOLD = 40.0  # Score 40-69% → DISTRACTED
                                        # Score < 40%  → LOOKING_AWAY

# Focus duration tracking
FOCUS_STREAK_RESET_FRAMES = 10    # Consecutive non-center frames to reset streak

# ──────────────────────────────────────────────
# Visualization Colors (BGR for OpenCV)
# ──────────────────────────────────────────────
VIS_COLORS = {
    "eye_contour":      (255, 200, 50),    # Cyan-ish blue
    "iris_center":      (0, 255, 200),     # Bright green-yellow
    "iris_ring":        (0, 255, 255),     # Yellow
    "gaze_arrow":       (100, 255, 100),   # Green
    "focus_indicator":  (0, 255, 0),       # Pure green (focused)
    "distracted_indicator": (0, 200, 255), # Orange
    "away_indicator":   (0, 0, 255),       # Red
    "text_bg":          (30, 30, 30),      # Dark background for text
    "text_fg":          (255, 255, 255),   # White text
}

# Arrow / indicator sizing
GAZE_ARROW_LENGTH    = 40     # pixels
GAZE_ARROW_THICKNESS = 2
IRIS_DOT_RADIUS      = 3
EYE_CONTOUR_THICKNESS = 1

# Focus indicator position (top-right corner offset)
FOCUS_INDICATOR_X_OFFSET = 20
FOCUS_INDICATOR_Y_OFFSET = 30
FOCUS_INDICATOR_RADIUS   = 8
