import { BookOpen, LifeBuoy, FileCode2, MessageSquare } from 'lucide-react';
import PageHeader from '../components/Cards/PageHeader';

export default function Help() {
  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <PageHeader title="Help & Support" subtitle="Documentation, FAQs, and system support" breadcrumb={['TrueView AI', 'Help']} />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
        <div className="glass p-6 rounded-2xl flex items-start gap-4 hover:border-primary-500/30 transition-colors cursor-pointer group">
          <div className="w-12 h-12 rounded-xl bg-primary-500/10 flex items-center justify-center text-primary-400 group-hover:scale-110 transition-transform"><BookOpen size={24}/></div>
          <div>
            <h3 className="text-base font-bold text-gray-100 mb-1">Documentation</h3>
            <p className="text-sm text-gray-500">Comprehensive guides on setting up and using the AI Proctoring system.</p>
          </div>
        </div>
        <div className="glass p-6 rounded-2xl flex items-start gap-4 hover:border-primary-500/30 transition-colors cursor-pointer group">
          <div className="w-12 h-12 rounded-xl bg-accent-500/10 flex items-center justify-center text-accent-400 group-hover:scale-110 transition-transform"><LifeBuoy size={24}/></div>
          <div>
            <h3 className="text-base font-bold text-gray-100 mb-1">Support Tickets</h3>
            <p className="text-sm text-gray-500">Contact our technical team for assistance with critical issues.</p>
          </div>
        </div>
      </div>

      <div className="glass p-8 rounded-2xl">
        <h3 className="text-lg font-bold text-gray-100 mb-6">Frequently Asked Questions</h3>
        <div className="space-y-4">
          {[
            { q: "How does the AI Risk Score calculation work?", a: "The risk score is a composite metric generated by combining individual confidence scores from the face detection, liveness, audio analysis, and gaze tracking models. A higher score indicates a higher probability of academic dishonesty." },
            { q: "Are the camera feeds recorded locally or in the cloud?", a: "By default, streams are processed in memory and discard unless flagged for review. If storage is enabled in settings, encrypted snippets surrounding the alert are saved securely to your specified storage provider." },
            { q: "Can I use custom YOLO weights for object detection?", a: "Yes. In the backend ai-service directory, you can drop your custom .pt files into the object_detection/weights folder and update the pipeline configuration to reference them." }
          ].map((faq, i) => (
            <div key={i} className="pb-4 border-b border-white/[0.04] last:border-0 last:pb-0">
              <h4 className="text-sm font-semibold text-gray-200 mb-2 flex items-center gap-2"><MessageSquare size={14} className="text-primary-400"/> {faq.q}</h4>
              <p className="text-sm text-gray-500 pl-5">{faq.a}</p>
            </div>
          ))}
        </div>
      </div>
      
      <div className="text-center mt-12">
        <p className="text-xs text-gray-600 font-mono">TrueView AI Core Version 1.0.0-rc.2</p>
      </div>
    </div>
  );
}
