"""
Object Tracker Metadata Parser – TrueView AI

Stateful tracking parser that records specific object instances,
monitoring appearance time, disappearance time, and movement trajectories.
"""

import time

class ObjectTracker:
    """
    Tracks state of individual object IDs generated by YOLO over time.
    """
    
    def __init__(self):
        # Dict mapping tracking ID -> object metadata
        # Key: track_id (int)
        # Value: {
        #   "label": str,
        #   "first_seen": float (timestamp),
        #   "last_seen": float (timestamp),
        #   "last_position": list [cx, cy],
        #   "total_movement": float (cumulative pixels moved)
        # }
        self.tracked_objects = {}
        
    def update_tracks(self, detections: list) -> list:
        """
        Update tracked objects metadata with current detections.
        
        Args:
            detections: List of current frame detections from YoloDetector
            
        Returns:
            list of dict: updated detections enriched with trajectory history.
        """
        now = time.time()
        updated_detections = []
        active_ids = set()
        
        for det in detections:
            track_id = det["track_id"]
            label = det["label"]
            x1, y1, x2, y2 = det["box"]
            cx = (x1 + x2) / 2.0
            cy = (y1 + y2) / 2.0
            
            # If object has no tracking ID (standard fallback), skip tracking metadata enrichment
            if track_id is None:
                updated_detections.append(det)
                continue
                
            active_ids.add(track_id)
            
            if track_id not in self.tracked_objects:
                # First time seeing this object ID
                self.tracked_objects[track_id] = {
                    "label": label,
                    "first_seen": now,
                    "last_seen": now,
                    "last_position": [cx, cy],
                    "total_movement": 0.0
                }
            else:
                # Existing object, check for movement displacement
                meta = self.tracked_objects[track_id]
                prev_cx, prev_cy = meta["last_position"]
                displacement = ((cx - prev_cx)**2 + (cy - prev_cy)**2)**0.5
                
                meta["last_seen"] = now
                meta["last_position"] = [cx, cy]
                meta["total_movement"] += displacement
                
            meta = self.tracked_objects[track_id]
            first_seen_time = meta["first_seen"]
            duration_active = now - first_seen_time
            
            enriched_det = {
                **det,
                "appearance_time": round(first_seen_time, 1),
                "duration_seconds": round(duration_active, 1),
                "total_movement_px": round(meta["total_movement"], 1)
            }
            updated_detections.append(enriched_det)
            
        # Optional: Clean up objects not seen for a long time (e.g. > 10 seconds)
        # to avoid memory leaks during long examinations
        expired_ids = []
        for tid, meta in self.tracked_objects.items():
            if tid not in active_ids and now - meta["last_seen"] > 10.0:
                expired_ids.append(tid)
                
        for tid in expired_ids:
            del self.tracked_objects[tid]
            
        return updated_detections
        
    def reset(self):
        """Reset tracking database."""
        self.tracked_objects.clear()
